### ISSUE TITLE
能简单介绍一下动画的逻辑吗？

### ISSUE THREAD

**Issue by NilPixel** [nostarsnow/typeMonkey.js#1]
大神，能简单介绍一下动画的逻辑吗？特别是旋转那一块的处理

**Comment by nostarsnow** [comment]
大神不敢当。我一直想着写文档的。一直又懒得写。
我还是写出来吧。
大致就是根据上一块的最长一行和最后一行以及下一块的最长一行和第一行来判断旋转的origin。

**Comment by nostarsnow** [comment]
> 大神，能简单介绍一下动画的逻辑吗？特别是旋转那一块的处理

大神不敢当。我一直想着写文档的。一直又懒得写。
我还是写出来吧。
大致就是根据上一块的最长一行和最后一行以及下一块的最长一行和第一行来判断旋转的origin。

**Comment by TnZhao** [comment]
多谢

**Comment by NilPixel** [comment]
> > 大神，能简单介绍一下动画的逻辑吗？特别是旋转那一块的处理
> 
> 大神不敢当。我一直想着写文档的。一直又懒得写。
> 我还是写出来吧。
> 大致就是根据上一块的最长一行和最后一行以及下一块的最长一行和第一行来判断旋转的origin。

多谢
