### ISSUE TITLE
请问，这个基于javascrip制作的 web动画 可以转化成mp4视频吗？

### ISSUE THREAD

**Issue by zhouchichun** [nostarsnow/typeMonkey.js#3]

**Comment by nostarsnow** [comment]
哈哈。不瞒你说。我还真的想过。。。毕竟对标的就是APP制作视频的功能嘛。
不过嘛。
一方面。因为web功能不支持。要想实现就只能用软件录屏了。
另一方面。如果要做视频。直接用快手/抖音/字说APP就好了。制作的视频会更精美。
