### ISSUE TITLE
求问 gulp server怎么用  我master分支没有dev文件夹

### ISSUE THREAD

**Issue by MagicBoBo** [nostarsnow/typeMonkey.js#4]

**Comment by nostarsnow** [comment]
额。。。文档我啥也没写。哈哈。
直接运行`gulp`即可启动。dev文件是gulp生成的。

**Comment by MagicBoBo** [comment]
好的，3q


 
---原始邮件---
发件人: "nostar"<notifications@github.com>
发送时间: 2019年7月24日(星期三) 下午2:31
收件人: "nostarsnow/typeMonkey.js"<typeMonkey.js@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"jingbo"<350464406@qq.com>;
主题: Re: [nostarsnow/typeMonkey.js] 求问 gulp server怎么用  我master分支没有dev文件夹 (#4)



额。。。文档我啥也没写。哈哈。
 直接运行gulp即可启动。dev文件是gulp生成的。
